### ISSUE TITLE
Code Chasnges

### ISSUE THREAD

**Issue by RuchinBuena** [deepakbuena/asa#4]
1. Remove private keyword from variable Line 76.
2, line 230 Use String.isNotBlank() function,
3.  Dynamic query should be builded by querybilder.

**Comment by deepakbuena** [comment]
1. Remove private keyword from variable Line 76. - Completed
2. line 230 Use String.isNotBlank() function, - Completed
3. Dynamic query should be builded by querybilder. - As discussed will be completed in next phase

@RuchinBuena

**Comment by RuchinBuena** [comment]
All has been fixed
